version: "3.8"

services:
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123
    volumes:
      - mongodb-data:/data/db
    networks:
      - micro-net
    deploy:
      replicas: 1

  users-service:
    image: users-service:1.0
    ports:
      - "5000:5000"
    environment:
      - MONGO_HOST=mongodb
      - JWT_SECRET=secret
    networks:
      - micro-net
    deploy:
      replicas: 1

  movies-service:
    image: movies-service:1.0
    ports:
      - "5001:5001"
    environment:
      - MONGO_HOST=mongodb
      - REVIEWS_SERVICE_HOST=reviews-service
    networks:
      - micro-net
    deploy:
      replicas: 1

  reviews-service:
    image: reviews-service:1.0
    ports:
      - "5002:5002"
    environment:
      - MONGO_HOST=mongodb
    networks:
      - micro-net
    deploy:
      replicas: 1

  api-gateway:
    image: api-gateway:1.0
    ports:
      - "8080:80"
    networks:
      - micro-net
    deploy:
      replicas: 1

volumes:
  mongodb-data:

networks:
  micro-net:
    driver: overlay
    attachable: true